name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: [main]

concurrency: ci-${{ github.ref }}

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      redis:
        image: redis
        ports: ["6379:6379"]

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install system dependencies
        run: sudo apt-get -y update

      - name: Rubocop
        run: bundle exec rubocop --fail-fast

      - name: Build assets
        run: bundle exec rails assets:precompile

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec --fail-fast
